backend:
  name: github
  repo: albo3/tw5
  branch: main # Branch to update (e.g. "main" or "master")

media_folder: "assetsP/images/uploads" # Folder where images are stored in your repo
public_folder: "/assetsP/images/uploads" # Folder where images are accessible in the browser

collections:
  - name: "pages"
    label: "Pages"
    files:
      - name: "index"
        label: "Home Page"
        file: "index.html"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - name: "about"
        label: "About Page"
        file: "about.html"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
